### ISSUE TITLE
Demo gifs missing, k8s.rip urls -> 404

### ISSUE THREAD

**Issue by unfo** [bgeesaman/malicious-compliance#4]
demo0.gif works as it is present in the repo.

Slide 18/44 has link https://k8s.rip/demo-os which redirects to https://github.com/bgeesaman/malicious-compliance/blob/main/demo/demo1.gif

21/44 https://k8s.rip/demo-pkg -> https://github.com/bgeesaman/malicious-compliance/blob/main/demo/demo2gif (also note: demo2gif not demo2.gif)

24/44 https://k8s.rip/demo-symlink -> https://github.com/bgeesaman/malicious-compliance/blob/main/demo/demo3.gif

27/44 https://k8s.rip/demo-pack -> https://github.com/bgeesaman/malicious-compliance/blob/main/demo/demo4.gif

30/44 https://k8s.rip/demo-zero -> https://github.com/bgeesaman/malicious-compliance/blob/main/demo/demo5.gif

33/44 https://k8s.rip/demo-sbom -> https://github.com/bgeesaman/malicious-compliance/blob/main/demo/sbom.gif

Made this issue to make you aware of the missing files, if it was unintentional.

But based on the slides I definitely want to watch the recording, very promising results :)

**Comment by bgeesaman** [comment]
Thanks for the reminder!  I’ll recut the gifs and reply back to this. (We made several last minute changes before the talk, so all the gifs needed re-recording to match).

**Comment by bgeesaman** [comment]
Ok, all set! Thanks again
